### ISSUE TITLE
New cloud category

### ISSUE THREAD

**Issue by noraj** [mBouamama/rawsec_cli#196]
**Describe the solution you'd like**

Hi @mBouamama.

Firstly, thanks again for your great tool.

I wanted to inform you I added a [cloud](https://gitlab.com/rawsec/rawsec-cybersecurity-list/-/issues/113) category in the Tools section.

It may require some modifications.

**Comment by mBouamama** [comment]
hi @noraj long time ago,
Normally new category will be availabe on the fly without new release.
You can try: `rawsec-cli list tools cloud` or `rawsec-cli search pacu`.
