### ISSUE TITLE
Can we have better output?

### ISSUE THREAD

**Issue by giteshnxtlvl** [mBouamama/rawsec_cli#198]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/58145476/120996085-de81a100-c73a-11eb-942c-85fc856326e6.png)

- Output is messy in tabular form
- Can't read description properly
- Can't click hyperlink directly, one have to go back 2 times in terminal to copy the whole link of project.

**Describe the solution you'd like**
List output + Color would be better.
```
JWT-Key-Recovery
    Recover the public key used to sign JWT tokens
    https://github.com/FlorianPicca/JWT-Key-Recovery
    [Python]

JWT cracker
    Multi-threaded JWT brute-force cracker
    https://github.com/brendan-rius/c-jwt-cracker 
    https://lmammino.github.io/distributed-jwt-cracker/
    [C] [Paid] [Kali linux: jwt-cracker]
```

- Now user can directly click the link.
- No extra white space and fields like keywords
- Simple and better output + colors.

**Comment by mBouamama** [comment]
hi @giteshnxtlvl,
Great Idea, I will work on that.

**Comment by giteshnxtlvl** [comment]
Thanks @mBouamama and it will be great if you can remain this tools to only `rawsec`

**Comment by mBouamama** [comment]
Hi @giteshnxtlvl ,
Package name was chosen by @noraj Creator & Maintainer of [Rawsec's CyberSecurity Inventory](https://inventory.rawsec.ml/tools.html)
Let's see pull request: #15

**Comment by mBouamama** [comment]
Are you ok with that?
![image](https://user-images.githubusercontent.com/57527739/122129539-8c293a00-ce36-11eb-9edd-afab188abd03.png)

**Comment by giteshnxtlvl** [comment]
Output looks Awesome, Nice work @mBouamama :)

**Comment by giteshnxtlvl** [comment]
As rawsec is deprecated, so now `rawsec-cli` can be `rawsec`. Any thoughts @noraj?
https://github.com/mBouamama/rawsec_cli/packages/532825

**Comment by noraj** [comment]
@mBouamama For [pass-station](https://github.com/sec-it/pass-station) I have made several output format:

> Output: simple table, pretty table, JSON, YAML, CSV

See [examples][https://sec-it.github.io/pass-station/#/pages/examples) ([source code](https://github.com/sec-it/pass-station/blob/master/lib/pass_station/output.rb))

So maybe you can keep the pretty table format and propose an alternative list format you jest implemented. Also JSON is good for API interfacing and CSV for CLI grepping.

**Comment by noraj** [comment]
> As rawsec is deprecated, so now `rawsec-cli` can be `rawsec`. Any thoughts @noraj?
> https://github.com/mBouamama/rawsec_cli/packages/532825

I prefer we keep `rawsec-cli` cmd and `rawsec_cli` package name, I find `rawsec` too confusing with the whole [Rawsec](https://raw.pm/) brand.

**Comment by giteshnxtlvl** [comment]
>  I find rawsec too confusing with the whole Rawsec brand.

Rawsec CLI is ok, but command can be `rawsec` only. Just like AWS CLI's command is only `aws`.
Anyway I am ok either ways.

And don't forgot the logo for CLI,  as on typing `rawsec-cli` nothing appears.
