### ISSUE TITLE
Alternative data formats

### ISSUE THREAD

**Issue by noraj** [mBouamama/rawsec_cli#21]
The table output display nicely but having other output options could help for programmatic usage (JSON) or command piping (CSV).

**Comment by mBouamama** [comment]
it's a good idea, what you prefer?
- ` --ouput json` and `--ouput csv`
- `--json JSON_FILE_NAME (with a default JSON_FILE_NAME )`, `--csv CSV_FILE_NAME (with a default CSV_FILE_NAME )`
- an other idea?

**Comment by noraj** [comment]
maybe a bit of both `--ouput <json|csv|table>` that change the stdout outpout (to be able to pipe other commands) and `--output-file file.{json,cvs,txt}` to be able to export the result and auto-detecting the extension asked.

**Comment by mBouamama** [comment]
Done

**Comment by noraj** [comment]
Awesome work. I'll try that.
