### ISSUE TITLE
[chore] discussion

### ISSUE THREAD

**Issue by noraj** [mBouamama/rawsec_cli#25]
Hi, can you enable the beta discussion feature please

![image](https://user-images.githubusercontent.com/16578570/102014967-f57da280-3d58-11eb-9312-7d2abeb05cd5.png)

This will add a new tab where we can chat

![image](https://user-images.githubusercontent.com/16578570/102014982-fe6e7400-3d58-11eb-9bf5-a960ebf7ed83.png)

**Comment by mBouamama** [comment]
done
