### ISSUE TITLE
invalid JSON output

### ISSUE THREAD

**Issue by noraj** [mBouamama/rawsec_cli#45]
**Describe the bug**

`-of json` is fine and export json using double quotes, `-o json` is exporting json with single quotes which is invalid and so break all json parsers.

**To Reproduce**

```
$ rawsec-cli list os -of /tmp/test.json
$ rawsec-cli list os -o json > /tmp/test2.json
$ diff test.json test2.json
$ rawsec-cli list os -o json | jq             
parse error: Invalid numeric literal at line 1, column 12
$ cat test.json | jq # => ok
```

**Expected behavior**

- identic output between -o and -of
- -o json to return valid json

**Environment (please complete the following information):**
 - OS: AchLinux
 - Python Version 3.9.1
 - rawsec-cli, version: 1.1.1, commit: 1f86aed2a6c7af7d5b1e18eb1df043b7071247da

**Idea**

Just replace simple quotes with double quotes (or export python dict to JSON).

**Comment by mBouamama** [comment]
hey @noraj 
thanks you for testing my code, awesome work, thanks a lot.

True i just needed to replace:
**this code**:
```python
click.echo({"projects": projects, "total": len(projects)})
```
**By**:
```python
click.echo(json.dumps({"projects": projects, "total": len(projects)}))
```

now:
`rawsec-cli list os -o json | jq # => ok`

**Comment by noraj** [comment]
I had a good guss it was a python dict vs JSON object issue.

**Comment by mBouamama** [comment]
yes
